parameters:
  buildConfiguration: ''
  projects: ''
  strategies: []
  netSdkVersion: ''

jobs:
  - job: UnitTest
    displayName: Run unit tests
    strategy:
      matrix:
        ${{ each strategy in parameters.strategies }}:
          ${{ each pair in strategy }}:
            ${{ pair.key }}:
              VM_IMAGE: ${{ pair.value }}
    pool:
      vmImage: $(VM_IMAGE)

    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: ${{ parameters.netSdkVersion }}
          
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '${{ parameters.projects }}'          
        displayName: dotnet restore

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--no-restore --configuration $(buildConfiguration)'
          projects: '${{ parameters.projects }}'          
        displayName: dotnet build
              
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          arguments: '--no-build --configuration $(buildConfiguration) --collect "Code Coverage" --verbosity normal '
          publishTestResults: true
          projects: '${{ parameters.projects }}'          
        displayName: dotnet test
