parameters:
  vmImage: ''
  buildConfiguration: ''
  projects: ''
  arguments: ''
  netSdkVersion: ''

jobs:
  - job: IntegrationTests
    displayName: Run integration tests
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: ${{ parameters.netSdkVersion }}
          
          
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '${{ parameters.projects }}'          
          arguments: '${{ parameters.arguments }}'
        displayName: dotnet restore

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--no-restore --configuration $(buildConfiguration) ${{ parameters.arguments }}'
          projects: '${{ parameters.projects }}'          
        displayName: dotnet build

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          arguments: '--no-build --configuration $(buildConfiguration) --collect "Code Coverage" ${{ parameters.arguments }} --verbosity normal '
          publishTestResults: true
          projects: '${{ parameters.projects }}'          
        displayName: dotnet test
